[package]
name = "testify"
version = "0.1.0"
edition = "2021"

[dependencies]
extension-traits = "1.0.1"
fmt-derive = "0.1.2"
proc-macro2 = "1.0.85"
quote = "1.0.36"
syn = { version = "2.0.66", features = ["full", "printing", "visit", "visit-mut"] }
tinytemplate = "1.2.1"
